### ISSUE TITLE
Broken link: The Mistake at the Heart of Agile (and how to get past it)

### ISSUE THREAD

**Issue by genericmoniker** [JanVanRyswyck/awesome-talks#52]
I can't reach http://ndc2011.macsimum.no/mp4/Day1%20Wednesday/Track4%201500-1600.mp4 (nor anything at the ndc2011 subdomain).

**Comment by JanVanRyswyck** [comment]
That's unfortunate. I can't find any replacement video either. I might have the original downloaded somewhere, but I'm not sure about the legal implications when I try to upload it again somewhere. I removed the entry for now.
