### ISSUE TITLE
John Cleese Lecture on Creativity is not available anymore

### ISSUE THREAD

**Issue by nvinayshetty** [JanVanRyswyck/awesome-talks#54]
This  video is listed under title **Cognitive Development**
with the name 
**A Lecture on Creativity by John Cleese [36:09]**

**Comment by spidfire** [comment]
Can someone confirm this is the same? 

https://www.youtube.com/watch?v=PQ0lck7oo4A

**Comment by JanVanRyswyck** [comment]
I updated the link with the one provided by @spidfire. Thank you guys for pointing this out.

**Comment by spidfire** [comment]
In that case you can close this ticket
