### ISSUE TITLE
Add the publish date of the talk

### ISSUE THREAD

**Issue by internetbird** [JanVanRyswyck/awesome-talks#90]
Altough many of the talks listed here are generic and don't relate to a specifc version of techonology at a given time, it would be nice to have the date published in list details. For example:

The Computer Revolution hasn't happend yet by Alan Kay (1997) [1:04:34]

**Comment by spidfire** [comment]
Not be harsh but you could make a start and create a PR out of it :)

**Comment by internetbird** [comment]
Will create a PR for this. Thanks :)
